name: Normalize Markdown

on:
  push:
    paths:
      - "*.md"

permissions:
  contents: write

jobs:
  normalize:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref_name }}

      - name: Prettify markdown
        uses: creyD/prettier_action@v4.6
        with:
          no_commit: true
          prettier_options: --write **/*.md

      - name: Commit markdown changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ github.ref_name }}
          commit_message: Prettified markdown
          file_pattern: "*.md"
